Repository cypher-network/bamboo, pull requests merged in 2021-09, with the labels that each got.

#56 - (refactor): Renaming of wallet service, initial usage of in keyword.
  bamwallet/HD/CommandReceiver.cs
  bamwallet/HD/ICommandReceiver.cs
  cli/Commands/CmdLine/SyncCommand.cs
  cli/Commands/CmdLine/WalletAddressCommand.cs
  cli/Commands/CmdLine/WalletBalanceCommand.cs
  cli/Commands/CmdLine/WalletCreateCommand.cs
  cli/Commands/CmdLine/WalletCreateSeedCommand.cs
  cli/Commands/CmdLine/WalletListCommand.cs
  cli/Commands/CmdLine/WalletReceivePaymentCommand.cs
  cli/Commands/CmdLine/WalletRecoverTransactionsCommand.cs
  cli/Commands/CmdLine/WalletRestoreCommand.cs
  cli/Commands/CmdLine/WalletTransferCommand.cs
  cli/Commands/CmdLine/WalletTxHistoryCommand.cs
  cli/Commands/Common/Command.cs
  cli/Commands/Rpc/RcpCreateTransactionCommand.cs
  cli/Commands/Rpc/RpcCreateSeed.cs
  cli/Commands/Rpc/RpcCreateWalletCommand.cs
  cli/Commands/Rpc/RpcSpendCommand.cs
  cli/Commands/Rpc/RpcWalletAddressCommand.cs
  cli/Commands/Rpc/RpcWalletListCommand.cs
  cli/Commands/Rpc/RpcWalletReceive.cs
  cli/Commands/Rpc/RpcWalletTxHistoryCommand.cs
Labels: feature

#58 (bug): Deactivate pending Tx check.
  bamwallet/HD/CommandReceiver.cs
Labels: bug

#59 Wallet RCP create transaction
  bamwallet/HD/CommandReceiver.cs
  bamwallet/Helper/Util.cs
  bamwallet/Model/Vout.cs
  bamwallet/bamwallet.csproj
  cli/cli.csproj
Labels: refactoring
